export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const LOGIN_PATH = '/';
export const APP_PATH = '/app';
export const USER_PROFILE_UPDATE_SUCCESS = 'USER_PROFILE_UPDATE_SUCCESS';
export const USER_PROFILE_UPDATE_FAILED = 'USER_PROFILE_UPDATE_FAILED';