export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_FAILED = 'CREATE_USER_FALIED';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_LOADING = 'CREATE_USER_LOADING';
export const USER_LOG_IN_SUCCESS = 'USER_LOG_IN_SUCCESS';
export const USER_LOG_IN_FAILED = 'USER_LOG_IN_FAILED';
export const RESET_FIELD = 'RESET_FIELD';
export const USER_CAN_LOG_IN = 'USER_CAN_LOG_IN';